namespace Apex.Modules.Accounting.JournalEntries.Domain;

/// <summary>
/// Draft-time input for a single Journal Entry Line. The identity is generated by the caller
/// through <c>IIdGenerator</c>; row-number assignment is owned by the <see cref="JournalEntry"/>
/// aggregate. A null <see cref="RowNumber"/> requests automatic assignment.
/// </summary>
public sealed record JournalEntryLineInput(
    long Id,
    JournalEntrySide Side,
    decimal Amount,
    string AccountClassCode,
    string GeneralAccountCode,
    string SubsidiaryAccountCode,
    string? DetailAccountCode,
    string Description,
    int? RowNumber = null);
