using Apex.Application.Abstractions.Data;
using Apex.Modules.Accounting.ChartOfAccounts.Domain;
using Apex.Modules.Accounting.ChartOfAccounts.Repositories.Rows;
using Dapper;

namespace Apex.Modules.Accounting.ChartOfAccounts.Repositories;

internal sealed class AccountClassReadRepository(IGeneralConnectionFactory factory):IAccountClassReadRepository
{
 public async Task<AccountClassRow?> GetAsync(long id,CancellationToken ct=default)=>await (await factory.OpenAsync(ct)).QuerySingleOrDefaultAsync<AccountClassRow>(new CommandDefinition("SELECT id Id,code Code,name Name,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM account_class WHERE id=@Id",new{Id=id},cancellationToken:ct));
 public async Task<IReadOnlyList<AccountClassRow>> ListAsync(bool includeArchived,CancellationToken ct=default)=>(await (await factory.OpenAsync(ct)).QueryAsync<AccountClassRow>(new CommandDefinition("SELECT id Id,code Code,name Name,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM account_class WHERE @IncludeArchived=1 OR status='ACTIVE' ORDER BY code,id",new{IncludeArchived=includeArchived},cancellationToken:ct))).AsList();
}
internal sealed class GeneralAccountReadRepository(IGeneralConnectionFactory factory):IGeneralAccountReadRepository
{
 public async Task<GeneralAccountRow?> GetAsync(long id,CancellationToken ct=default)=>await (await factory.OpenAsync(ct)).QuerySingleOrDefaultAsync<GeneralAccountRow>(new CommandDefinition("SELECT id Id,account_class_id AccountClassId,code Code,name Name,nature Nature,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM general_account WHERE id=@Id",new{Id=id},cancellationToken:ct));
 public async Task<IReadOnlyList<GeneralAccountRow>> ListAsync(bool includeArchived,CancellationToken ct=default)=>(await (await factory.OpenAsync(ct)).QueryAsync<GeneralAccountRow>(new CommandDefinition("SELECT id Id,account_class_id AccountClassId,code Code,name Name,nature Nature,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM general_account WHERE @IncludeArchived=1 OR status='ACTIVE' ORDER BY code,id",new{IncludeArchived=includeArchived},cancellationToken:ct))).AsList();
}
internal sealed class SubsidiaryAccountReadRepository(IGeneralConnectionFactory factory):ISubsidiaryAccountReadRepository
{
 public async Task<SubsidiaryAccountRow?> GetAsync(long id,CancellationToken ct=default)=>await (await factory.OpenAsync(ct)).QuerySingleOrDefaultAsync<SubsidiaryAccountRow>(new CommandDefinition("SELECT id Id,general_account_id GeneralAccountId,code Code,name Name,nature Nature,detail_account_type DetailAccountType,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM subsidiary_account WHERE id=@Id",new{Id=id},cancellationToken:ct));
 public async Task<IReadOnlyList<SubsidiaryAccountRow>> ListAsync(bool includeArchived,CancellationToken ct=default)=>(await (await factory.OpenAsync(ct)).QueryAsync<SubsidiaryAccountRow>(new CommandDefinition("SELECT id Id,general_account_id GeneralAccountId,code Code,name Name,nature Nature,detail_account_type DetailAccountType,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM subsidiary_account WHERE @IncludeArchived=1 OR status='ACTIVE' ORDER BY code,id",new{IncludeArchived=includeArchived},cancellationToken:ct))).AsList();
}

internal sealed class AccountClassWriteRepository(IGeneralConnectionFactory factory):IAccountClassWriteRepository
{
 public async Task<AccountClass?> GetForUpdateAsync(long id,CancellationToken ct=default){var r=await (await factory.OpenAsync(ct)).QuerySingleOrDefaultAsync<AccountClassRow>(new CommandDefinition("SELECT id Id,code Code,name Name,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM account_class WITH(UPDLOCK,ROWLOCK) WHERE id=@Id",new{Id=id},factory.Transaction,cancellationToken:ct));return r is null?null:AccountClass.Rehydrate(r.Id,r.Code,r.Name,r.Status.ToAccountStatus(),r.CreatedAt,r.UpdatedAt,r.ArchivedAt);}
 public async Task<bool> CodeExistsAsync(string code,long? excludingId=null,CancellationToken ct=default)=>await (await factory.OpenAsync(ct)).ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(1) FROM account_class WITH(UPDLOCK,HOLDLOCK) WHERE code=@Code AND (@ExcludingId IS NULL OR id<>@ExcludingId)",new{Code=code,ExcludingId=excludingId},factory.Transaction,cancellationToken:ct))>0;
 public Task<bool> HasActiveChildrenAsync(long id,CancellationToken ct=default)=>Exists("SELECT COUNT(1) FROM general_account WITH(UPDLOCK,HOLDLOCK) WHERE account_class_id=@Id AND status='ACTIVE'",id,ct);
 public Task InsertAsync(AccountClass v,CancellationToken ct=default)=>Exec("INSERT INTO account_class(id,code,name,status,created_at) VALUES(@Id,@Code,@Name,@Status,@CreatedAt)",new{v.Id,v.Code,v.Name,Status=v.Status.ToDatabaseValue(),v.CreatedAt},ct);
 public Task UpdateAsync(AccountClass v,CancellationToken ct=default)=>Exec("UPDATE account_class SET name=@Name,status=@Status,updated_at=@UpdatedAt,archived_at=@ArchivedAt WHERE id=@Id",new{v.Id,v.Name,Status=v.Status.ToDatabaseValue(),v.UpdatedAt,v.ArchivedAt},ct);
 private async Task<bool> Exists(string sql,long id,CancellationToken ct)=>await (await factory.OpenAsync(ct)).ExecuteScalarAsync<int>(new CommandDefinition(sql,new{Id=id},factory.Transaction,cancellationToken:ct))>0;
 private async Task Exec(string sql,object args,CancellationToken ct){var count=await (await factory.OpenAsync(ct)).ExecuteAsync(new CommandDefinition(sql,args,factory.Transaction,cancellationToken:ct));if(count!=1)throw new InvalidOperationException("Expected one account class row to be affected.");}
}
internal sealed class GeneralAccountWriteRepository(IGeneralConnectionFactory factory):IGeneralAccountWriteRepository
{
 public async Task<GeneralAccount?> GetForUpdateAsync(long id,CancellationToken ct=default){var r=await (await factory.OpenAsync(ct)).QuerySingleOrDefaultAsync<GeneralAccountRow>(new CommandDefinition("SELECT id Id,account_class_id AccountClassId,code Code,name Name,nature Nature,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM general_account WITH(UPDLOCK,ROWLOCK) WHERE id=@Id",new{Id=id},factory.Transaction,cancellationToken:ct));return r is null?null:GeneralAccount.Rehydrate(r.Id,r.AccountClassId,r.Code,r.Name,r.Nature.ToAccountNature(),r.Status.ToAccountStatus(),r.CreatedAt,r.UpdatedAt,r.ArchivedAt);}
 public async Task<bool> CodeExistsAsync(long parentId,string code,long? excludingId=null,CancellationToken ct=default)=>await (await factory.OpenAsync(ct)).ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(1) FROM general_account WITH(UPDLOCK,HOLDLOCK) WHERE account_class_id=@ParentId AND code=@Code AND (@ExcludingId IS NULL OR id<>@ExcludingId)",new{ParentId=parentId,Code=code,ExcludingId=excludingId},factory.Transaction,cancellationToken:ct))>0;
 public async Task<bool> HasActiveChildrenAsync(long id,CancellationToken ct=default)=>await (await factory.OpenAsync(ct)).ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(1) FROM subsidiary_account WITH(UPDLOCK,HOLDLOCK) WHERE general_account_id=@Id AND status='ACTIVE'",new{Id=id},factory.Transaction,cancellationToken:ct))>0;
 public Task InsertAsync(GeneralAccount v,CancellationToken ct=default)=>Exec("INSERT INTO general_account(id,account_class_id,code,name,nature,status,created_at) VALUES(@Id,@AccountClassId,@Code,@Name,@Nature,@Status,@CreatedAt)",new{v.Id,v.AccountClassId,v.Code,v.Name,Nature=v.Nature.ToDatabaseValue(),Status=v.Status.ToDatabaseValue(),v.CreatedAt},ct);
 public Task UpdateAsync(GeneralAccount v,CancellationToken ct=default)=>Exec("UPDATE general_account SET name=@Name,status=@Status,updated_at=@UpdatedAt,archived_at=@ArchivedAt WHERE id=@Id",new{v.Id,v.Name,Status=v.Status.ToDatabaseValue(),v.UpdatedAt,v.ArchivedAt},ct);
 private async Task Exec(string sql,object args,CancellationToken ct){var n=await (await factory.OpenAsync(ct)).ExecuteAsync(new CommandDefinition(sql,args,factory.Transaction,cancellationToken:ct));if(n!=1)throw new InvalidOperationException("Expected one general account row to be affected.");}
}
internal sealed class SubsidiaryAccountWriteRepository(IGeneralConnectionFactory factory):ISubsidiaryAccountWriteRepository
{
 public async Task<SubsidiaryAccount?> GetForUpdateAsync(long id,CancellationToken ct=default){var r=await (await factory.OpenAsync(ct)).QuerySingleOrDefaultAsync<SubsidiaryAccountRow>(new CommandDefinition("SELECT id Id,general_account_id GeneralAccountId,code Code,name Name,nature Nature,detail_account_type DetailAccountType,status Status,created_at CreatedAt,updated_at UpdatedAt,archived_at ArchivedAt FROM subsidiary_account WITH(UPDLOCK,ROWLOCK) WHERE id=@Id",new{Id=id},factory.Transaction,cancellationToken:ct));return r is null?null:SubsidiaryAccount.Rehydrate(r.Id,r.GeneralAccountId,r.Code,r.Name,r.Nature.ToAccountNature(),r.DetailAccountType.ToDetailAccountType(),r.Status.ToAccountStatus(),r.CreatedAt,r.UpdatedAt,r.ArchivedAt);}
 public async Task<bool> CodeExistsAsync(long parentId,string code,long? excludingId=null,CancellationToken ct=default)=>await (await factory.OpenAsync(ct)).ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(1) FROM subsidiary_account WITH(UPDLOCK,HOLDLOCK) WHERE general_account_id=@ParentId AND code=@Code AND (@ExcludingId IS NULL OR id<>@ExcludingId)",new{ParentId=parentId,Code=code,ExcludingId=excludingId},factory.Transaction,cancellationToken:ct))>0;
 public Task InsertAsync(SubsidiaryAccount v,CancellationToken ct=default)=>Exec("INSERT INTO subsidiary_account(id,general_account_id,code,name,nature,detail_account_type,status,created_at) VALUES(@Id,@GeneralAccountId,@Code,@Name,@Nature,@DetailType,@Status,@CreatedAt)",new{v.Id,v.GeneralAccountId,v.Code,v.Name,Nature=v.Nature.ToDatabaseValue(),DetailType=v.DetailAccountType.ToDatabaseValue(),Status=v.Status.ToDatabaseValue(),v.CreatedAt},ct);
 public Task UpdateAsync(SubsidiaryAccount v,CancellationToken ct=default)=>Exec("UPDATE subsidiary_account SET name=@Name,status=@Status,updated_at=@UpdatedAt,archived_at=@ArchivedAt WHERE id=@Id",new{v.Id,v.Name,Status=v.Status.ToDatabaseValue(),v.UpdatedAt,v.ArchivedAt},ct);
 private async Task Exec(string sql,object args,CancellationToken ct){var n=await (await factory.OpenAsync(ct)).ExecuteAsync(new CommandDefinition(sql,args,factory.Transaction,cancellationToken:ct));if(n!=1)throw new InvalidOperationException("Expected one subsidiary account row to be affected.");}
}
